### ISSUE TITLE
Update docs to reflect breaking changes

### ISSUE THREAD

**Issue by felixbrucker** [balena-io-modules/resumable-request#6]
The current docs are outdated and apply to v1.0.1 but not to v2.0.0.

I personally use `resumable-request` with something like this:

```
const requestStream = progress(resumable(request, {
  url: myUrl,
  timeout: 1000 * 60 * 2,
}, {progressInterval: Number.MAX_SAFE_INTEGER}));
```

where i need a request object to be returned to use with other modules, which does not seem to be possible in v2.0.0, maybe i'm missing something?

I'll use v1.0.1 for now.

**Comment by zxfrank** [comment]
I'm facing the same issue, looks like v2 has switched to 'simple-get' and do not accept the request instance as 1st argument.
